version: "3.7"

services:
  sample:
    container_name: bank_project
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
